######################################################################
# Automatically generated by qmake (2.01a) mar. févr. 8 19:53:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FenAide.h FenApropos.h FenPrincipale.h
SOURCES += FenAide.cpp FenApropos.cpp FenPrincipale.cpp main.cpp
LIBS += -L/usr/local/lib -lgmpxx -lgmp 
