######################################################################
# Automatically generated by qmake (2.01a) mer. févr. 9 12:32:02 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FenPrincipale.h
SOURCES += FenPrincipale.cpp main.cpp
TRANSLATIONS += qtprojet_en.ts
LIBS += -L/usr/local/lib -lgmpxx -lgmp 
