######################################################################
# Automatically generated by qmake (2.01a) mer. févr. 9 12:32:02 2011
######################################################################

TEMPLATE = app
TARGET = rsa_encode
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FenPrincipale.hpp
SOURCES += FenPrincipale.cpp main.cpp
TRANSLATIONS += trRsa-encoding_en.ts
LIBS += -L/usr/local/lib -lgmpxx -lgmp
QT += widgets
CONFIG += debug
