######################################################################
# Automatically generated by qmake (2.01a) mer. févr. 9 12:32:02 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FenRsa-encoding.hpp
SOURCES += FenRsa-encoding.cpp main.cpp
TRANSLATIONS += trRsa-encoding_en.ts
LIBS += -L/usr/local/lib -lgmpxx -lgmp
